# Generated by Django 2.2.7 on 2022-02-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0003_auto_20190220_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsdevicecategory',
            name='name',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('WIFI', 'Wifi Device'), ('SETTOPBOX', 'Settop Box'), ('MODEM', 'Modem')], default='UNKNOWN', max_length=100, unique=True),
        ),
    ]
