# Generated by Django 2.2.7 on 2022-09-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0003_auto_20190220_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsdevicemodel',
            name='acs_connectionrequest_digest_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acsdevicecategory',
            name='name',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('WIFI', 'Wifi Device'), ('SETTOPBOX', 'Settop Box'), ('MODEM', 'Modem')], default='UNKNOWN', max_length=100, unique=True),
        ),
    ]
