# Generated by Django 2.2.7 on 2022-09-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0004_auto_20220204_0900'),
        ('acs', '0004_auto_20220923_0842'),
    ]

    operations = [
    ]
