# Generated by Django 2.2.7 on 2022-10-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0005_merge_20220923_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='acssession',
            name='hook_state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
