# Generated by Django 2.2.7 on 2022-10-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0006_acssession_hook_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsdevicemodel',
            name='config_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='acsdevicemodel',
            name='preconfig_template',
            field=models.TextField(blank=True, default=''),
        ),
    ]
