# Generated by Django 2.2.7 on 2022-10-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0007_auto_20221025_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsdevicemodel',
            name='tracked_parameters',
            field=models.TextField(blank=True, default=''),
        ),
    ]
