# Generated by Django 2.2.7 on 2022-10-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0008_acsdevicemodel_tracked_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsdevice',
            name='firmware_only',
            field=models.BooleanField(default=False),
        ),
    ]
