# Generated by Django 2.2.7 on 2022-10-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0009_acsdevice_firmware_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsdevicemodel',
            name='xmpp_template',
            field=models.TextField(blank=True, default=''),
        ),
    ]
