# Generated by Django 2.2.7 on 2022-11-01 09:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0010_acsdevicemodel_xmpp_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsdevice',
            name='hook_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
