# Generated by Django 2.2.7 on 2022-11-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0012_auto_20221101_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsdevice',
            name='acs_connectionrequest_url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
