# Generated by Django 2.2.7 on 2022-11-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0013_acsdevice_acs_connectionrequest_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsdevice',
            name='acs_connectionrequest_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
