# Generated by Django 2.2.7 on 2022-11-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0015_auto_20221109_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acsdevice',
            name='firmware_only',
        ),
    ]
