# Generated by Django 2.2.7 on 2022-11-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0016_remove_acsdevice_firmware_only'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acsdevice',
            old_name='get_full_parameters',
            new_name='full_parameters_request',
        ),
    ]
