# Generated by Django 2.2.7 on 2022-11-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0017_auto_20221114_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsdevice',
            name='factory_default_request',
            field=models.BooleanField(default=False),
        ),
    ]
