# Generated by Django 2.2.7 on 2022-11-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0018_acsdevice_factory_default_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsdevice',
            name='connection_request',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
