# Generated by Django 3.2 on 2023-10-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0020_acssession_access_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsdevice',
            name='acs_full_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acsdevice',
            name='hook_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acsdevicemodel',
            name='acs_parameter_map_overrides',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acssession',
            name='hook_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
