# Generated by Django 3.2 on 2023-10-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0021_auto_20231011_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acshttprequest',
            name='acs_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acs_http_requests', to='acs.acssession'),
        ),
        migrations.AlterField(
            model_name='acshttpresponse',
            name='http_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acs_http_response', to='acs.acshttprequest'),
        ),
        migrations.AlterField(
            model_name='acshttpresponse',
            name='rpc_response_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rpc_responses', to='acs.acshttprequest'),
        ),
        migrations.AlterField(
            model_name='acssession',
            name='acs_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acs_sessions', to='acs.acsdevice'),
        ),
    ]
