# Generated by Django 3.2 on 2023-10-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0022_auto_20231019_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsqueuejob',
            name='acs_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acs_queue_jobs', to='acs.acsdevice'),
        ),
    ]
