# Generated by Django 3.2 on 2023-10-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0023_alter_acsqueuejob_acs_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsqueuejob',
            name='handled_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queuejobs', to='acs.acshttpresponse'),
        ),
    ]
