# Generated by Django 4.2 on 2024-03-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0024_alter_acsqueuejob_handled_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsdevice',
            name='desired_preconfig_level',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
