# Generated by Django 4.2 on 2024-04-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0027_alter_acsdevicemodel_vendor_config_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acsdevicemodel',
            old_name='vendor_config_files',
            new_name='vendor_config_file',
        ),
    ]
