# Generated by Django 5.2.10 on 2026-02-25 09:07

import acs.models.acs_device_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0029_alter_acsdevicemodel_vendor_config_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsdevicemodel',
            name='config_template',
            field=models.TextField(blank=True, default='', validators=[acs.models.acs_device_model.validate_yaml]),
        ),
        migrations.AlterField(
            model_name='acsdevicemodel',
            name='preconfig_template',
            field=models.TextField(blank=True, default='', validators=[acs.models.acs_device_model.validate_yaml]),
        ),
        migrations.AlterField(
            model_name='acsdevicemodel',
            name='tracked_parameters',
            field=models.TextField(blank=True, default='', validators=[acs.models.acs_device_model.validate_yaml]),
        ),
        migrations.AlterField(
            model_name='acsdevicemodel',
            name='xmpp_template',
            field=models.TextField(blank=True, default='', validators=[acs.models.acs_device_model.validate_yaml]),
        ),
    ]
