# Generated by Django 5.2.10 on 2026-07-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0030_alter_acsdevicemodel_config_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsdevicemodel',
            name='inform_spread_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
